# Generated by Django 2.2.5 on 2019-10-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
