# Generated by Django 2.2.5 on 2019-10-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='desc',
        ),
    ]
