# Generated by Django 2.2.5 on 2019-10-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_service_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('desc', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics/Event')),
            ],
        ),
    ]
