# Generated by Django 2.2.1 on 2019-11-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='available',
            field=models.IntegerField(default=10),
        ),
    ]
