# Generated by Django 2.2.1 on 2019-11-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rooms_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Rooms')),
            ],
        ),
    ]
