# Generated by Django 2.2.1 on 2019-11-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verified',
            name='user',
        ),
    ]
